"""
Pydantic data models for AEGIS RPA Backend.

This module defines all request/response models used throughout the application,
including task instructions, execution sessions, status updates, and history.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Literal
from datetime import datetime
from enum import Enum
from dataclasses import dataclass


class TaskInstructionRequest(BaseModel):
    """Request model for submitting a new task instruction."""
    instruction: str = Field(..., min_length=1, max_length=1000)


class TaskInstructionResponse(BaseModel):
    """Response model after submitting a task instruction."""
    session_id: str
    status: Literal["pending", "in_progress"]
    message: str


class SubtaskStatus(str, Enum):
    """Enumeration of possible subtask statuses."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class Subtask(BaseModel):
    """Model representing a single subtask within an execution session."""
    id: str
    description: str
    status: SubtaskStatus
    tool_name: Optional[str] = None
    tool_args: Optional[dict] = None
    result: Optional[dict] = None
    error: Optional[str] = None
    timestamp: datetime


class ExecutionSession(BaseModel):
    """Model representing a complete execution session."""
    session_id: str
    instruction: str
    status: Literal["pending", "in_progress", "completed", "failed", "cancelled"]
    subtasks: List[Subtask] = []
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime] = None


class StatusUpdate(BaseModel):
    """Model for WebSocket status updates sent to the frontend."""
    session_id: str
    subtask: Optional[Subtask] = None
    overall_status: str
    message: str
    window_state: Optional[Literal["minimal", "normal"]] = None
    timestamp: datetime


class SessionSummary(BaseModel):
    """Model for summarized session information in history lists."""
    session_id: str
    instruction: str
    status: str
    created_at: datetime
    completed_at: Optional[datetime] = None
    subtask_count: int


class HistoryResponse(BaseModel):
    """Response model for history endpoint."""
    sessions: List[SessionSummary]
    total: int


class ErrorResponse(BaseModel):
    """Model for error responses."""
    error: str
    details: Optional[str] = None
    session_id: Optional[str] = None


class ValidationResult(BaseModel):
    """Model for validation results from pre-processing."""
    is_valid: bool
    error_message: Optional[str] = None


class ExecutionPlan(BaseModel):
    """Model for execution plans generated by ADK agent."""
    instruction: str
    subtasks: List[dict]
    estimated_duration: Optional[int] = None
    created_at: datetime


class ToolResult(BaseModel):
    """Model for results returned by RPA tools."""
    success: bool
    data: Optional[dict] = None
    error: Optional[str] = None


class ActionResult(BaseModel):
    """Model for results from RPA engine actions."""
    success: bool
    retry_count: int
    error: Optional[str] = None


@dataclass
class LauncherConfig:
    """Configuration for Local App Launcher timing and paths."""
    mapping_file: str = "config/app_mappings.json"
    menu_open_delay: float = 1.0
    typing_interval: float = 0.1
    search_delay: float = 1.0
    launch_delay: float = 2.0
    verification_timeout: float = 5.0
    max_instruction_words: int = 10
